### ISSUE TITLE
Switch Dialog in the same Skill

### ISSUE THREAD

**Issue by mohandivraniya** [microsoft/botframework-skills#123]
## User Story
I would like to have a feature in a skill to switch between dialog in the same skill.
## Acceptance Criteria 
*List your requirements.*
The best way to implement switching dialog in the skill.
## Resources
*NA*

## Notes
*Provide any additional information.*

**Comment by xieofxie** [comment]
@mohandivraniya One way to do this is via RouteStepAsync. For example, in POI skill, 
* mark ShouldInterrupt when some intent is identified https://github.com/microsoft/botframework-skills/blob/1ef8d3421036be6107f864a5a9d9ecf23d33de2d/skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs#L985
* Cancel in the following step https://github.com/microsoft/botframework-skills/blob/1ef8d3421036be6107f864a5a9d9ecf23d33de2d/skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs#L530
* Skip intro to route https://github.com/microsoft/botframework-skills/blob/1ef8d3421036be6107f864a5a9d9ecf23d33de2d/skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs#L236

This is definitely not the best way, it is just a hint.

**Comment by bobokids** [comment]
We created the new calendar skill in Composer and leverage the capability of interruption and dialog switch support in Adaptive dialog in latest SDK. Please try the new skill and let us know if you need more scenario support in term of dialog switching.
