### ISSUE TITLE
Update skills from latest Skill Template

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-skills#124]
There have been several updates to the Skill template that should be replicated in the skill projects. The skill template in the next branch has all of the changes, and these two PRs can be used for reference:

- https://github.com/microsoft/botframework-solutions/pull/3218
- https://github.com/microsoft/botframework-solutions/pull/3207

**Comment by bobokids** [comment]
follow this commit for fix for #3064.
https://github.com/microsoft/botframework-solutions/commit/e369a099cca1fd2c9fb29a99ac2b559c981eac5e

**Comment by xieofxie** [comment]
@lauren-mills are sample and template synchronized now? For example, these two files are different: https://github.com/microsoft/botframework-solutions/blob/next/samples/csharp/skill/SkillSample.Tests/SkillSample.Tests.csproj https://github.com/microsoft/botframework-solutions/blob/next/templates/csharp/Skill/Skill.Tests/Skill.Tests.csproj 
Which one should we follow? The template? Thanks!

**Comment by bobokids** [comment]
done for all skills.
