### ISSUE TITLE
[Microsoft][MsTeams][Task Module][Scroll bars issue in task module]

### ISSUE THREAD

**Issue by Sujit-Gaikwad** [microsoft/botframework-skills#162]
#### What project is affected?
Task Module in bot

#### What happens?
Hi teams,

I am using MS Task module to render web page in bot on teams channel. Web page is getting display  in task module but I'm not able to scroll the page and scroll bar in task module page also not get rendered as well 

please help me on this

regards and thanks,
sujit

**Comment by xieofxie** [comment]
Hi @Sujit-Gaikwad, I tried and found scroll bars are displayed (fixed width & height for task module):
![image](https://user-images.githubusercontent.com/2876650/79088272-b552c400-7d74-11ea-8459-773f04103e14.png)

I am just using a simple web from https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules:
```
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <div id="embed-container">
        <iframe width="1000" height="700" src="https://www.youtube.com/embed/rd0Rd8w3FZ0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe>
    </div>
</body>
</html>
```

I think you should adjust your css etc. Thanks

**Comment by Sujit-Gaikwad** [comment]
Hi xieofxie ,
I am getting vertical scroll bar in task module but not able to scroll the page using that.
I am able to scroll the page using mouse scroll button but using scroll bar it is not getting scrolled

![Screenshot (4)](https://user-images.githubusercontent.com/60354515/80090247-d5586380-857c-11ea-95af-f86c74988086.png)

**Comment by Sujit-Gaikwad** [comment]
>>This repo is for bot skills and I am afraid we don't know **how to solve Teams issues**

@xieofxie as per your comment if it is Teams issues can it be forwarded to Teams.

**Comment by xieofxie** [comment]
@Gousia-MSFT Could you help to triage this? I don't know who should this be forwarded to. Thanks

**Comment by xieofxie** [comment]
Manually **transferred** to https://github.com/MicrosoftDocs/msteams-docs/issues/1627 since it is a Teams issue. Close here now.
