### ISSUE TITLE
ITSM SKILL (Experimental Skill of Microsoft)

### ISSUE THREAD

**Issue by SavitaKumari-NTT** [microsoft/botframework-skills#186]
Except experimental skills all skills uses the Bot Framework Solutions Beta Release 0.8.
As per this release ActivityHandlerDialog.cs has been deprecated and replaced with a Waterfall Dialog implementation in the MainDialog of the Virtual Assistant and Skill templates.
More details you can verify in below links:
https://microsoft.github.io/botframework-solutions/overview/whats-new/0.8-beta/Summary/
https://microsoft.github.io/botframework-solutions/overview/whats-new/0.8-beta/maindialog-updates/
https://microsoft.github.io/botframework-solutions/virtual-assistant/handbook/activity-flow/

Some of the experimental skills still uses the ActivityHandlerDialog(Now deprecated)  in its MainDialog and some experimental skills uses the RouterDialog(Now deprecated) in its MainDialog. 
[Note: RouterDialog replace with ActivityHandlerDialog and now ActivityHandlerDialog replace with Waterfall Dialog.
https://github.com/microsoft/botframework-solutions/issues/3092
https://github.com/microsoft/botframework-solutions/pull/2585]
So  experimental skills (e.g ITSM Skill) should work properly if ActivityHandlerDialog replaced with a Waterfall Dialog implementation in the MainDialog. Due to this reason ITSM skill is not working as per expected even properly setup on ServiceNow and successfully deployed on Azure Portal.

When ITSM skill will be available with latest code on Github?

**Comment by xieofxie** [comment]
@SavitaKumari-NTT It seems you used ITSM skill directly. The sources of these packages are configured in this file https://github.com/microsoft/botframework-skills/blob/master/skills/csharp/Directory.Build.props in the solutions project.

You could add them manually to your sources:
* https://botbuilder.myget.org/F/aitemplates/api/v3/index.json
* https://botbuilder.myget.org/F/botbuilder-v4-dotnet-daily/api/v3/index.json
* https://www.myget.org/F/botbuilder-community-dotnet/api/v3/index.json

**Comment by bobokids** [comment]
@SavitaKumari-NTT , please reactivate this issue if you have more question.
