### ISSUE TITLE
Include Teams Integration into calendar Skill

### ISSUE THREAD

**Issue by Jibin12345** [microsoft/botframework-skills#189]
Include  a Teams link along with the Calendar skill output. Currently the calendar skill output is limited to a new meeting created in outlook with no meeting links. We’d like the capability to have a teams meeting link and phone in details be embedded in this newly create event

**Comment by gayathrir8** [comment]
Kindly bring in this enhancement. Having Teams integration should be good, so that when users open the meeting created they can see the Join Meeting Teams links. 

Additionally if the Team Meeting details can be displayed in the adaptive card post confirmation, would be beneficial.

**Comment by bobokids** [comment]
Create a Teams meeting link when create new meeting. Show the link when user show meeting details.

**Comment by bobokids** [comment]
Merged.
