### ISSUE TITLE
Calendar Skill integration >> Issues with closing a flow

### ISSUE THREAD

**Issue by gayathrir8** [microsoft/botframework-skills#193]
Virtual Agent Details:
1.	Bot framework Version :  V4 : 4.8.0 version Microsoft Bot Builder
2.	Services used: LUIS, QnA, Speech, Insights & Analytics
3.	Language: C#
4.	Channels : Webchat, Directline
5.	Access points: Website , Mobile app (Tablets, Mobile, Desktop supported)
6.	Bot Template: Virtual Assistant Template
7.	Skills used: Calendar skill
8.	Status: In production (without skill)
9.	Current Issue: Unable to continue use cases in bot after accessing skill.
10.	Detailed Error: 
“Our VA template is developed with Bot Builder version 4.6 and we have made minimal code changes to integrate with the calendar skill. Presently we are faced with the following challenges on the "EndOfconversation" from calendar skill bot.

1.	"Value cannot be null" error prompting from Skill Controller "ReplyToActivityAsync" override method.
Error Details:
On completion of every dialog flow , the calendar skill bot responds with an activity type of "EndOfconversation" .From this, we have understood that the "EndOfconversation" closes the channel connectivity and returns back with the ChannelData parameter as null. As a reply to this activity, our VA tries to send a “typing” activity, back to the calendar skill which then eventually turns into "value cannot be null" error.

Note: In our VA we are inheriting “RouterDialog” in the “MainDialog” class. Also in every turn context, the dialog continuation is handled by the “OnTurnAsyc” method in “DialogBot.cs” file(which inherits TeamsActivityHandler)

Could you please advise us with any best practices available on responding to the  "EndOfConversation"  activity from the Skill dialogue?

Screenshot:
 

2.	Calendar Skill Luis not working properly, on the utterances like "schedule a meeting with <username >". Do we require any training or updates  in the existing calendar skill Luis model?.”

**Comment by gayathrir8** [comment]
Attaching insights error log

**Comment by xieofxie** [comment]
Hi @gayathrir8, for the first problem, in the VA side, if it receives a EndOfConversation from Skill, it should end the current SkillDialog directly. You can see the current SkillDialog implementation here https://github.com/microsoft/botbuilder-dotnet/blob/0d37b11feb262e59825838c0c5fbf745385d062c/libraries/Microsoft.Bot.Builder.Dialogs/SkillDialog.cs#L73

From your description, you are mixing 4.6 & 4.8 and this is not recommended. When using VA with Skills, they should use same version of SDK.

For the second problem, if you feel the current Luis model unsatisfactory, you could update it directly in the portal https://www.luis.ai/ after deployment.

Thanks

**Comment by bobokids** [comment]
@gayathrir8, please re-activate the issue if you have more comments.
