### ISSUE TITLE
Include SSO automatically as part of Calendar skill integration with VA

### ISSUE THREAD

**Issue by gayathrir8** [microsoft/botframework-skills#194]
As a user I want to be able to access the skills without having to login again inside chat window. Currently, after integrating with VA, I have to click login button, and copy paste a Code to continue flow.

Acceptance:
User says "Create new meeting at 7PM" automatically skill is invoked and flow continues

**Comment by bobokids** [comment]
There would be new calendar experience with VA scaler core. Close this issue for now.
