### ISSUE TITLE
Who Skill shows the Person card after all responses

### ISSUE THREAD

**Issue by darrenj** [microsoft/botframework-skills#200]
When you ask "Who is Darren" we show the Person Adaptive Card response which is great. However, if I ask "What office is Darren in" or "What is Darren's Telephone Number" it gives me a text response with the office number of telephone which is great but **also** then shows me the adaptive card which doesn't feel right.

Removing the ShowItem `ReplaceDialog` was the fix I used in my local copy:

![image](https://user-images.githubusercontent.com/33519520/81002646-809cce80-8e41-11ea-939a-3e3604bfd750.png)

**Comment by darrenj** [comment]
After one of the reviews it's been pointed out this is how Teams works today with the Who Skill so this will need some design review before we choose which way to go.

**Comment by bobokids** [comment]
This is a remaining issue in whobot. We have no plan to update whobot for Fe. Close this issue for now.
