### ISSUE TITLE
Package referenced in skill samples has unvailable dependencies

### ISSUE THREAD

**Issue by VladPapacostea-SM** [microsoft/botframework-skills#210]
#### What project is affected?
Calendar Skill
(but really, all projects that reference Microsoft.Bot.Solutions 1.0.0)

#### What language is this in?
C#
#### What happens?

<PackageReference Include="Microsoft.Bot.Solutions" Version="1.0.0" />
has dependencies on 

![image](https://user-images.githubusercontent.com/26440696/81671682-23a4a800-9441-11ea-9305-86085a773df9.png)

and versions to match those constraints are not available ( not even from the separate feed https://botbuilder.myget.org/F/aitemplates/api/v3/index.json ) 

#### What are the steps to reproduce this issue?

Pull Skill sample from master. 
Remove all non-publicly available feeds from your package manager.
Clear your packages folder. 
Try to restore/build 

#### What were you expecting to happen?
Restore/Build/Use sample successfully

**Comment by xieofxie** [comment]
Hi, these packages are public available here https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily like https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder.AI.Luis/4.9.0-rc1.

The sources of these packages are configured in this file https://github.com/microsoft/botframework-skills/blob/master/skills/csharp/Directory.Build.props.

**Comment by VladPapacostea-SM** [comment]
Got it, thanks @xieofxie . Wasn't expecting a stable 1.0.0 version to depend on a nightly build.
Happy to close.
