### ISSUE TITLE
SkillServiceLibrary package has not been updated with the latest functionality to reflect the one used in the skill samples

### ISSUE THREAD

**Issue by VladPapacostea-SM** [microsoft/botframework-skills#213]
#### What project is affected?
All skills/samples
#### What language is this in?
C#
#### What happens?
The dependency referenced in the skill samples, SkillServiceLibrary, which your code currently uses through a project reference, was previously available in a nuget package as seen below: 
![image](https://user-images.githubusercontent.com/26440696/81804031-6a150800-9510-11ea-867d-2cd1fe63113b.png)

Currently, the updated functionality in the latest version of the code from the sample repo in the shared project is ahead of the package available through nuget. This obivously causes issues when updating the base code of the skills to match the latest version of the samples.

#### What were you expecting to happen?
The SkillServiceLibrary package to be updated, reflecting the latest functionality of the "shared" project.

**Comment by xieofxie** [comment]
Thanks! We will update it soon

**Comment by bobokids** [comment]
seems the package already be removed.

**Comment by davidmcgowan** [comment]
@bobokids what do you mean by removed? 

I notice that the shared SkillServiceLibrary project was updated only a few days before your reply while the nuget package was not updated to reflect these changes. 

I am also still seeing three references in the calendar skill sample to the shared SkillServiceLibrary project.

**Comment by xieofxie** [comment]
Hi @davidmcgowan the calendar skill references the SkillServiceLibrary via project instead of nuget package https://github.com/microsoft/botframework-skills/blob/master/skills/csharp/calendarskill/CalendarSkill.csproj

**Comment by davidmcgowan** [comment]
@xieofxie are there any plans to update the nuget to reflect the changes in SkillServiceLibrary project?

**Comment by xieofxie** [comment]
@davidmcgowan No, we removed it in nuget. If you would like to use Calendar only without dependencies, you could copy the content of this library into Calendar. It doesn't contain many codes and you could remove unused codes in this way.
Thanks
