### ISSUE TITLE
Who skill throws an exception in expression for utterance "who are the peers of joni"

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botframework-skills#215]
#### What project is affected?
Who skill

#### What happens?
Ask "who are the peers of joni" with Megan account and get error:

```
Expression evaluation resulted in an error. Expression: =conversation.pageIndex * conversation.pageSize. Error: conversation.pageSize is not a number.
```
#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/43043272/81997721-79c24880-9605-11ea-8b83-899d33360fa0.png)

**Comment by darrenj** [comment]
Thanks Ryan - I've spotted this a few times. Restarting the conversation state seems to help so might be a memory issue

**Comment by ssss141414** [comment]
Hi, it seems to be fixed in latest code.
![image](https://user-images.githubusercontent.com/18118994/82062538-d9e7e600-96fc-11ea-9702-a9a9b0e4d0c7.png)
As darren said, this is because memory dosen't init. So if you find this bug again in latest code, please let me know.
Thanks!

**Comment by bobokids** [comment]
Ryan, let us know if this still repro.
