### ISSUE TITLE
Error in adding PointOfInterest skill to VA. 

### ISSUE THREAD

**Issue by VatsalaSingh** [microsoft/botframework-skills#279]
I'm trying to add PointOfInterest skill to my Virtual Assistant. I'm getting the following error. In this snapshot, I'm currently in my VA directory. I've added the LUIS path of the skill.
![skillerror](https://user-images.githubusercontent.com/25271116/86962603-ceef8600-c180-11ea-8c9f-2b8a5119e6b1.JPG)

How can I resolve this?

**Comment by xieofxie** [comment]
Hi @VatsalaSingh I have tested it on master of this repo and solutions repo and it worked correctly. Do you use the latest tool? https://www.npmjs.com/package/botskills

**Comment by VatsalaSingh** [comment]
@xieofxie yes I'm using the latest tool. First I created a skill project from VS (https://microsoft.github.io/botframework-solutions/skills/tutorials/create-skill/csharp/3-create-your-skill/) and added that to my VA. That successfully worked. The issue seems to be with sample skills.

**Comment by xieofxie** [comment]
@VatsalaSingh Oh, I figured out the reason from your screen shot. It seems the tool forget to quote `bf luis:convert` for the `out` parameter. Note the Command is `bf luis:convert ... --out C:\Users\vasingh\Desktop\sample skills\botframework-skills-master ...` and the error is unexpected argument `skills\botframework-skills-master ...`.

If you put it in a path without space it should be fine and I will create an issue about this.

**Comment by VatsalaSingh** [comment]
Right, it works now.  Thanks :)
