### ISSUE TITLE
Issue with ludown in Calendar skill

### ISSUE THREAD

**Issue by GitDruid** [microsoft/botframework-skills#282]
#### What project is affected?
Calendar skill

#### What language is this in?
C#

#### What happens?
Prebuilt entities for Italian locale causes parsing issues.

#### What are the steps to reproduce this issue?
Please refer to the following issues:
https://github.com/microsoft/botbuilder-tools/issues/1453
https://github.com/microsoft/botbuilder-tools/issues/1007

#### Question (sorry for posting here)
@munozemilio informed me that ludown is deprecated. But skills projects still use it? Is it planned to be replaced?

**Comment by xhr0804** [comment]
@GitDruid Hi, the skills projects has been updated to use bf-cli instead of ludown now. You can refer to the latest master branch.

**Comment by GitDruid** [comment]
> @GitDruid Hi, the skills projects has been updated to use bf-cli instead of ludown now. You can refer to the latest master branch.

Thanks @xhr0804. Do you know when the switch was done?

**Comment by xhr0804** [comment]
@GitDruid  Not exactly, but at least three or four months ago

**Comment by GitDruid** [comment]
> @GitDruid Not exactly, but at least three or four months ago

@xhr0804 mm... I will do some other test as soon as possible. Consider that I get the error above with code retrieved just one week ago.

**Comment by xhr0804** [comment]
@GitDruid 
For the prebuilt entity personName, it/de/fr/es can not support it now so I just submitted a PR to remove it from the .lu files.
For the datetimeV2, looks like Italian locale can not support it either.https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-prebuilt-entities#italian-entity-support. I will update the .lu soon.

**Comment by bobokids** [comment]
Log an issue in https://github.com/microsoft/Recognizers-Text/issues/2234 to track the datetimev2 support for it-it.
Close this issue.
