### ISSUE TITLE
Calendar skill meeting showing UTC in Outlook When trying to Edit

### ISSUE THREAD

**Issue by Jibin12345** [microsoft/botframework-skills#295]
After scheduling a meeting in EST Timezone , In Outlook(Time Zone is set to EST) when we try to edit the created meeting the start time and end time is being displayed in "(UTC) Coordinated Universal Time" What is the reason for such a behavior. 
![image](https://user-images.githubusercontent.com/44056324/90274389-1d79f980-de7e-11ea-9131-caa2f472b36c.png)

**Comment by SanjuJayakumarNair** [comment]
I am also facing the same issue when trying to edit its showing **(UTC) Coordinated Universal Time**

**Comment by peterinnesmsft** [comment]
We have a PR out to address this issue currently - see linked above.

**Comment by bobokids** [comment]
code merged.
