### ISSUE TITLE
Look up event(s): Day overview

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-skills#297]
## User Story
**As an** employee of an enterprise 
**I want** to as the skill about my day ahead
**so that** I can quickly see what events are coming up.

## Description
This feature should enable the user to provide natural language queries to access their events from the MS Graph API for a given date, date range, time, time range, or datetime range.

## Conversation Design
[Transcript](https://www.figma.com/file/xsSfVmzSe5CyFlcLovplS9/Calendar-Skill?node-id=26%3A1)

[Card design and considerations](https://www.figma.com/file/xsSfVmzSe5CyFlcLovplS9/Calendar-Skill?node-id=180%3A4)

## Language Understanding
| Intent | Sample Utterances | Prebuilt Entities | Custom Entities | Patterns |
| ------ | ----------------------| ----------------- | ----------------- | --------- |
| GetEventsByDate | What's on my calendar today? <br> Read me my calendar <br> Do I have an event tomorrow? <br> What's on my agenda this weekend? <br> List all events for August 20th | DatetimeV2 | - | - |

#### GetEventsByDate
* If no datetimev2 entity provided in initial utterance, default to today’s date
* If datetimev2 entity without date is provided (i.e. time or time range) default to today’s date at that time/time range.
* If datetimev2 entity is provided with only duration (i.e. 1 hour) default to today’s date.
* Call SearchEvents dialog to execute the Microsoft Graph API call and provide dialog.datetime in dialog options.
* Call SortEvents action on the results to prepare data for the adaptive card.

#### GetEventsByResponse
* If no datetimev2 entity provided in initial utterance, default to today’s date
* If datetimev2 entity without date is provided (i.e. time or time range) default to today’s date at that time/time range.
* If datetimev2 entity is provided with only duration (i.e. 1 hour) default to today’s date.
* Call SearchEvents dialog to execute the Microsoft Graph API call and provide dialog.datetime and dialog.responseType in dialog options.
* Call SortEvents action on the results to prepare data for the adaptive card.

#### SearchEvents
* Collect parameters from dialog options (datetime, responseType).
* Call MS Graph – Search Events action with provided parameters (datetime, responseType, token, time zone)
* Return results of API call in EndDialog action

## Custom Actions
| Name | Input | Output | Notes |
| ------ | ------ | -------- | ------- |
| ParseTimex | LUIS datetimeV2 timex array | Collection of parsed results | |
| MS Graph - Search Events | Start <br> End <br> Time zone <br> Response <br> Title <br> Description <br> Attendees | Collection of event objects | |
| MS Graph - Sort Events | Collection of event objects | Sorted and grouped events by date into previous and upcoming | |

## State Properties
| Scope | Property | Type | Notes |
| ------- | --------- | ----- | ------- |
| user | token | TokenResponse object from OAuth Prompt | |
| user | settings.mailboxSettings.timeZone | Time zone string (i.e. Pacific Standard Time) from user's MS Graph MailBotSettings (see Get User Settings feature) | |
| conversation | events | Collection of event objects | |
| dialog | datetime | DateTime object | |

#### Teams
Teams can support task modules, which might be useful for this feature in the future but is not in scope for this work item.
Suggested actions are not supported in Teams. All suggested actions in the designs should be rendered as card actions in Teams and suggested actions in all other channels. This may be handled automatically by the BF SDK but should be tested to verify.

## Acceptance Criteria
- [ ] Flow should work in both Direct mode (connecting to the skill bot directly) and in Skill mode (connecting through a VA).
- [x] Should be deployed in a testing environment for review.
- [ ] Flow should work and render correctly in Teams on Desktop, Web, Mobile, and Mac. There may be additional work on cards and other attachments to ensure compatibility.
- [x] Flow should work and render correctly in Web Chat.
- [ ] Flow should work in Direct Line Speech and should follow the design for speech scenarios.
- [ ] Each response (excluding card responses) should have at least 3 variant LG responses.
- [x] Each response and card should include speak property provided by design team.
- [ ] Help and Cancel interruptions should be implemented and customized for this dialog where relevant
- [ ] Should include supporting unit tests for both custom actions and declarative dialogs.
- [x] Language model should be tested against other intents to ensure that there is adequate training data to prevent conflicts
- [x] Supported languages: English

**Comment by lauren-mills** [comment]
Note on Teams compatibility.

Teams has a message size limit of 28kb ([source](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)). This means we are limited to the amount of information we can pass in an Adaptive Card. The larger card with the "see more" dropdown and the line item dropdowns exceeds this limit when there are more than approximately 5 events to show. This results in a "bad request" error.

This is being taken as a bug and will be resolved in a future sprint.

**Comment by Quirinevwm** [comment]
--- Design update end of week (25-09) ---
- missing transcript > 6 meetings included
