### ISSUE TITLE
Look up event(s): Search

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-skills#304]
## User Story
**As an** employee of an enterprise 
**I want** to ask VA to find a meeting for me, I will call out details that are top of mind such as start time and attendee (*could include title meeting if it’s easy to remember). 
**so that** I find the meeting I want to know more about and potentially take action

## Conversation Design
[Design](https://www.figma.com/file/xsSfVmzSe5CyFlcLovplS9/Calendar-Skill?node-id=26%3A1)
[Transcript](https://microsoft.sharepoint-df.com/:x:/t/BotFrameworkSolutions/Eer8FvZT2DhPmYMBfRVa7X4Bf9R0w6Bm9JJn5y8sd50g4A?e=iiHTaQ)
[Card design and considerations](https://www.figma.com/file/xsSfVmzSe5CyFlcLovplS9/Calendar-Skill?node-id=180%3A4)

## Language Understanding
| Intent | Sample Utterances | Prebuilt Entities | Custom Entities | Patterns |
| ------ | ----------------------| ----------------- | ----------------- | --------- |
GetEventTitle | | | | |
GetEventAttendees | | | | |
GetEventTime | | | | |
GetEventLocation | | | | |

## Dialogs
GetEventTitleDialog
- Collect parameters from LUIS entities. If not provided, prompt for which meeting.
- Call the SearchEventsDialog with parameters as options
- Display relevant LG response from Excel transcript 

GetEventAttendeesDialog
- Collect parameters from LUIS entities. If not provided, prompt for which meeting.
- Call the SearchEventsDialog with parameters as options
- Display relevant LG response from Excel transcript 

GetEventTimeDialog
- Collect parameters from LUIS entities. If not provided, prompt for which meeting.
- Call the SearchEventsDialog with parameters as options
- Display relevant LG response from Excel transcript 

GetEventLocationDialog
- Collect parameters from LUIS entities. If not provided, prompt for which meeting.
- Call the SearchEventsDialog with parameters as options
- Display relevant LG response from Excel transcript 

SearchEventsDialog
* Collect parameters from dialog options (title, datetime, and/or attendee).
* Call MS Graph – Search Events action with parameters
* Return results of API call in EndDialog action

## Custom Actions
| Name | Input | Output | Notes |
| ------ | ------ | -------- | ------- |
| MS Graph - Search Events | Start <br> End <br> Time zone <br> Title <br> Description <br> Attendees <br> **Ordinal (next)** | Collection of event objects | |

## State Properties
| Scope | Property | Type | Notes |
| ------- | --------- | ----- | ------- |
| user | token | TokenResponse object from OAuth Prompt | |
| user | settings.mailboxSettings.timeZone | Time zone string (i.e. Pacific Standard Time) from user's MS Graph MailBotSettings (see Get User Settings feature) | |
| conversation | events | Collection of event objects | |

## Channels
N/A

## Acceptance Criteria
- [ ] Flow should work in both Direct mode (connecting to the skill bot directly
~- [ ] Flow should work in Skill mode (connecting through a VA).~ This is on hold until a central VA can be created and deployed
- [ ] Should be deployed in a testing environment for review.
- [ ] Flow should work and render correctly in Teams on Desktop
- [ ] Flow should be tested in Teams for Mac and Teams for Mobile and any compatibility issues should be documented in a comment on this issue
- [ ] Flow should work and render correctly in Web Chat.
- [ ] Flow should work in Direct Line Speech and should follow the design~~ for speech scenarios.
- [ ] Each response (excluding card responses) should have at least 3 variant LG responses.
- [ ] Each response and card should include speak property provided by design team.
~- [ ] Help and Cancel interruptions should be implemented and customized for this dialog where relevant~ This requires greater all up design input
- [ ] Should include supporting unit tests for both custom actions and declarative dialogs.
- [ ] Language model should be tested against other intents to ensure that there is adequate training data to prevent conflicts
- [ ] Supported languages: English

**Comment by lauren-mills** [comment]
@xhr0804 - I added the ordinal parameter to the custom action. We need to be able to pass in "next" so we can use this dialog as the base for the CheckAvailability feature as well. Let me know if you have any questions!

**Comment by Quirinevwm** [comment]
--- Design update end of week (25-09) ---
- Transcript for disambiguation "Find Meeting": 2/3/4/5/>5 events '10 events this month' the card is sticky (next/previous/1st/2nd) except for 'show more'

- Update show more in lists throughout design: 
New logic: first the card shows items from 1-5 and 6-10 is hidden. Then user says "show more", bot will show a new card with 6-10 and 11-15 is hidden. 
If a user clicks on the chevron to open up, that is something we can't control - plus they are in click modality. So if they then ask to show more, they will see the 6-10 again plus 11-15 by opening up the chevron. 

- Decision to show result for >5 events that match search query '"Find Meeting": let's go per default for a month as max time, so a user will be able to search a month ahead. For 2,3,4,5 events search result we show no limitation on max time. Lauren Mills let's discuss this logic if that is oke?

- Update transcript when user continues with next, when it's at the end of the card (5 times) - show more options then > final ending "That was it, you are at the end of the list." 

- Overall transcript update numerical: currently 1-5, include 6,7,8,9,10th option (not that this use case is that common)

**Comment by xhr0804** [comment]
We may fully implemented the ChooseMultipleMeeting flow after the ChooseOption pattern #318 checked in?
