### ISSUE TITLE
Manage event(s): Create event

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-skills#307]
## User Story
**As an** employee at an Enterprise
**I want** VA to create an event for me that requires me to give relevant details only
**so that** I save as much time as possible

## Conversation Design
[Design](https://www.figma.com/file/xsSfVmzSe5CyFlcLovplS9/Calendar-Skill?node-id=215%3A15)
[Utterances and LG responses](https://microsoft.sharepoint-df.com/:x:/t/BotFrameworkSolutions/Eer8FvZT2DhPmYMBfRVa7X4Bf9R0w6Bm9JJn5y8sd50g4A?e=VmbzTe)

## Language Understanding
| Intent | Sample Utterances | Prebuilt Entities | Custom Entities | Patterns |
| ------ | ----------------------| ----------------- | ----------------- | --------- |
| CreateEvent | [Excel](https://microsoft.sharepoint-df.com/:x:/t/BotFrameworkSolutions/Eer8FvZT2DhPmYMBfRVa7X4Bf9R0w6Bm9JJn5y8sd50g4A?e=VmbzTe) | datetimev2, personName, emailAddress | title, location | - |

### CreateEventDialog
This dialog should do the following:
- Prompt for the name of the meeting. If the channel is DL Speech, skill should confirm the title with the user.
- Prompt for attendees via the GetContactsDialog. User should be able to skip adding attendees.
- If the user added attendees, the FindMeetingTimes API should be used to suggest times where all attendees are available within the user's working hours (working hours should be available in the user.settings.mailboxSettings state property). User should be able to specify they want to provide their own time.
- If there were no attendees or the user said they want to provide their own time, they should be prompted to for the datetime of the meeting. The ResolveDateTime action should be used to resolve the datetime from the user's utterance. 
     - If the user provided only a time, assume the date is the current date.
     - If the user provided only a date, prompt for a time
     - The default duration of an event should come from outlook settings. **Needs investigation to find this information. May need to add scopes to app registration. If not possible, default to 30 min.
- If there were attendees, a teams link should be added to the meeing, and they should be prompted to provide a physical location. User should be able to skip adding a physical location.
- User should confirm the event details using the same adaptive card from common.lg
- Once confirmed, the CreateEvents API should be used to create the event.
- The user should be able to use interruptions to modify properties of the event. Refer to the [Excel](https://microsoft.sharepoint-df.com/:x:/t/BotFrameworkSolutions/Eer8FvZT2DhPmYMBfRVa7X4Bf9R0w6Bm9JJn5y8sd50g4A?e=VmbzTe) transcript for examples of the interruptions that should be handled.

### GetContactDialog
This dialog should do the following:
- Accept recognized personName and emailAddress entities as dialog options
- If a personName or emailAddress were not provided, prompt for who should attend
- For each personName and/or emailAddress, do the following:
     - Lookup the name in the MS Graph Contacts and People APIs with the Contacts results taking priority
     - If there is only one result, that emailAddress from the contact result should be returned to the calling dialog. 
     - If there are multiple results from the contacts and people APIs combined, the user should be prompted to select one of the options.
     - The selected contact should be returned to the calling dialog.

## Custom Actions
| Name | Input | Output | Notes |
| ------ | ------ | -------- | ------- |
| MS Graph - Get Contacts | | | |
| MS Graph - Find Meeting Times | | | | 
| MS Graph - Create Event | | | |

## State Properties
| Scope | Property | Type | Notes |
| ------- | --------- | ----- | ------- |
| user | token | TokenResponse object from OAuth Prompt | |
| user | settings.mailboxSettings.timeZone | Time zone string (i.e. Pacific Standard Time) from user's MS Graph MailBoxSettings | |
| conversation | event | The newly created event item should be stored in conversation state for follow-up dialogs | |
| dialog | datetime | DateTime object | |

#### Teams
We may go back and add support for a TaskModule that allows the user to create an event using a form in Teams but that is out of scope for P0.

#### Speech
There is a variation in the flow for the speech channel to confirm the title of the event before continuing. This should only happen in DL Speech.

## Acceptance Criteria
- [ ] Flow should work in both Direct mode (connecting to the skill bot directly) and in Skill mode (connecting through a VA).
- [ ] Should be deployed in a testing environment for review.
- [ ] Flow should work and render correctly in Teams on Desktop, Web, Mobile, and Mac. There may be additional work on cards and other attachments to ensure compatibility.
- [ ] Flow should work and render correctly in Web Chat.
- [ ] Flow should work in Direct Line Speech and should follow the design for speech scenarios.
- [ ] Each response (excluding card responses) should have at least 3 variant LG responses.
- [ ] Each response and card should include speak property provided by design team.
- [ ] Help and Cancel interruptions should be implemented and customized for this dialog where relevant
- [ ] Should include supporting unit tests for both custom actions and declarative dialogs.
- [ ] Language model should be tested against other intents to ensure that there is adequate training data to prevent conflicts
- [ ] Supported languages: English

**Comment by Quirinevwm** [comment]
-- Design update end of week (25-09) ---
- Update show more in lists throughout design:
New logic: first the card shows items from 1-5 and 6-10 is hidden. Then user says "show more", bot will show a new card with 6-10 and 11-15 is hidden.
If a user clicks on the chevron to open up, that is something we can't control - plus they are in click modality. So if they then ask to show more, they will see the 6-10 again plus 11-15 by opening up the chevron.

- Update transcript when user continues with next, when it's at the end of the card (5 times) - show more options then > final ending "That was it, you are at the end of the list."

- Overall transcript update numerical: currently 1-5, include 6,7,8,9,10th option (not that this use case is that common)

- Include a comma between [Name], [email address]

- Confirmation transcript is missing after providing options, I've included in the transcript the following: 
![image](https://user-images.githubusercontent.com/43533472/94267243-8bb0e200-ff3b-11ea-9da0-4376455ffef4.png)
