### ISSUE TITLE
Test/Bug: Change wording button "launch survey" to "Provide feedback". 

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-skills#331]
Can we also make sure the element for survey pops up after you've tried out a few things, something like 5?10? actions? It interrupts my flow a lot now.

**Comment by lauren-mills** [comment]
I'll look into this. Right now, I have it launching at the end of a given flow. I think it should only launch when something ends though right, not after any given 5 actions right?

**Comment by Quirinevwm** [comment]
Update: as discussed in meeting, let's try to go for display to go to survey, after creation flow is completed/or failed - in the dogfood users can open up the feedback link via the .ppt also. Plus we can decide to show card for survey after an interaction of 15? and multiply so again after 30 etc.
