### ISSUE TITLE
Test/Bug: new branded content for dogfood (includes sign in text that is a bit longer, looks visually nicer)

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#333]
Additional content:
~~Welcome: "Hi there 🖐, great you are helping the VA Skills team out with this dogfood for calendar skill! You can ask the bot calendar related questions in this Teams chat modality (ps. other testing with modalities will follow, like speaking to the bot)~~
~~- Cancel/Stop: "OK, no problem I know I'm not perfect yet"~~
! More versions for Cancel: 
~~"Sure, I will cancel"
"OK, I will stop"~~

- End: "You've made it to the end 👏, thank you for helping us out!"
~~- Error: "I can tell there is something wrong here, can you please try again?
             "Oops, I'm stuck, can you try to ask me differently?"
             "Please help me out here, can you ask again but in a different way?"~~
~~- Sign in: Time to sign in to your Microsoft account to access your calendar, and try out our new Skill 💯 "~~

**Comment by Quirinevwm** [comment]
+ include new avatar can we try out the following options, to see which one works best:
(i) based on icon: https://microsoft.sharepoint-df.com/:i:/t/BotFrameworkVirtualAssistantScalerSkillPillarWorkingTeam/ERLyx-wMwOdKjpK8b_34Uo0ByF-CYSZn46Jj4NXjongAhg?e=uUd2n2
(ii) fun design: https://microsoft.sharepoint-df.com/:i:/t/BotFrameworkVirtualAssistantScalerSkillPillarWorkingTeam/EWKIM5NFQqZHrb1MYbwh4IoBJWiQI5Y4sDzlrmjT7RAXxg?e=YVZ5Bl

**Comment by Quirinevwm** [comment]
Include content for **Help**
"I can only help you out with Calendar related questions for now. For example, you can ask me: _"what's on for today"_, and _"create a new event"_. 

Change from what's currently there
![image](https://user-images.githubusercontent.com/43533472/98105764-acece280-1e98-11eb-8e9f-20f0ad548d71.png)

**Comment by lauren-mills** [comment]
@Quirinevwm - We don't have any logic for the end message right now. When do you want it to be displayed?

**Comment by Quirinevwm** [comment]
> n do you want

I was thinking we could leverage that content if they've "updated an event" that is the last action step in our dogfood + launch the survey button. I do see that it might be confusing, so let's skip that!

**Comment by Quirinevwm** [comment]
Update to search taking time:
**I'm searching your calendar, this might take a sec…
This might take a sec...
Hold on, this is taking a bit longer...
Hold on, I'm trying to find events that match**

**Comment by Quirinevwm** [comment]
@lauren-mills let's update the "sign-in" message, apparently it looks like an error in red the icon of 100 percent (lol).
Time to sign in with your Microsoft account to access your calendar, and try out our new 🗓 Skill "
![image](https://user-images.githubusercontent.com/43533472/98842548-07aead00-244a-11eb-8f10-f15ba8f72bf6.png)
