### ISSUE TITLE
Test/Bug: locale in meeting invite (with extreme links) & show the assistant booked it

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#337]
Meeting invite
- Include in invite: 
(font size 8)
**(avatar) This event was planned by a calendar bot**
- The Teams link is in full, usually it's "Click here to join the meeting"
![image](https://user-images.githubusercontent.com/43533472/97983517-b3665600-1dd5-11eb-91ce-09dd19767f8f.png)
- The links in the invite are way too elaborate, not like in a generic invite (especially when you check it on mobile)
- Generally my meetings are created in English, why did it pick up Dutch per default this time?
![image](https://user-images.githubusercontent.com/43533472/97983343-74380500-1dd5-11eb-8e34-ad5dab31fbf9.png)

**Comment by xhr0804** [comment]
I've found a way to fix the format, but still not sure how to change the locale to English.
Asked this quetion here https://stackoverflow.com/questions/64780710/how-to-book-a-teams-meeting-in-english-but-not-using-my-own-locale-in-graph-api

**Comment by Quirinevwm** [comment]
> I've found a way to fix the format, but still not sure how to change the locale to English.
> Asked this quetion here https://stackoverflow.com/questions/64780710/how-to-book-a-teams-meeting-in-english-but-not-using-my-own-locale-in-graph-api

Nice, yes let's see what they come back with, for now if you've fixed the visual format and own locale is oke.
Could you include above the dotted line the following still:
Avatar + _This event was planned by a calendar bot_
(font size 10, italic, and avatar fits that sizing)

Avatar: [link to our files on Teams](https://microsoft.sharepoint-df.com/:f:/t/BotFrameworkVirtualAssistantScalerSkillPillarWorkingTeam/EtwYFwVkxVdKqfr9lFcAWVMBTTmNTSPKLGnoyjDEBUCDnA?e=pAkwwh)
![image](https://user-images.githubusercontent.com/43533472/98813295-3d409f80-2424-11eb-97bc-94611a9b0619.png)

**Comment by lauren-mills** [comment]
Couldn't get the icon to show yet (a bit complicated to embed it through graph) but I added a robot emoji for now

**Comment by lauren-mills** [comment]
![image](https://user-images.githubusercontent.com/27976702/99140945-ed680100-25fa-11eb-8b79-3a92dc869f84.png)

**Comment by Quirinevwm** [comment]
@lauren-mills awesome plus the Teams links look normal now! 
We can also go for the generic 📅 calendar icon later, I like this dogfood bot avatar though 👍
