### ISSUE TITLE
error tolerance for "cancel" in Create flow 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/botframework-skills#339]
## Version
CalendarV2 

## Describe the bug
The context switching does not work for "cancel". 

## To Reproduce
![image](https://user-images.githubusercontent.com/43408889/98078344-dd3e7c00-1eac-11eb-96e3-6f6707ecaa90.png)

## Expected behavior
At least we should not complain the expression error.

**Comment by Quirinevwm** [comment]
#333 with updated transcript for cancel/stop

**Comment by KayMKM** [comment]
fixed by #355
