### ISSUE TITLE
Create meeting flow hit error

### ISSUE THREAD

**Issue by hibrenda** [microsoft/botframework-skills#340]
## Version
CalendarV2

## Describe the bug
Give a clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/43408889/98078842-cf3d2b00-1ead-11eb-9889-adfffe6f4f8b.png)

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by KayMKM** [comment]
@Quirinevwm The time suggestion list card is too long to showing in Teams. It looks this currently:
![image](https://user-images.githubusercontent.com/19773357/98090918-ae7dd100-1ebf-11eb-8fd1-c1aeb52760c7.png)
Can we remove the second line of "All participants can attend"?

**Comment by Quirinevwm** [comment]
> f "All participants ca

Yes let's take out the all participants can attend for now (will that work then?) - I will add that in the transcript though as additional text. We have a meeting in a minute, will edit this comment after that.

**Comment by KayMKM** [comment]
@Quirinevwm I think this design is for voice mode and the dog food version is chat mode. So I will change the response to following first:
- I have found multiple suggestions:
- There are multiple suggestions:
- I found more than one suggestion: 
- Hmm. I've found multiple suggestions:
- There seem to be a few suggestions:
- Looks like there are several suggestions:

**Comment by Quirinevwm** [comment]
> @Quirinevwm I think this design is for voice mode and the dog food version is chat mode. Current responses are:
> 
> * 2 attendees
>   
>   * I've found multiple suggestions when you can meet with {name}:
>   * I've found multiple suggestions when you can meet with {name}:
>   * I've found the following time when you can meet with {name}:
> * more than 2 attendees
>   
>   * I have found multiple suggestions:
>   * There are multiple suggestions:
>   * I found more than one suggestion:
>   * Uh oh. I've found multiple suggestions:
>   * There seem to be a few suggestions:
> 
> can we modify base on these responses?

**Comment by Quirinevwm** [comment]
> > @Quirinevwm I think this design is for voice mode and the dog food version is chat mode. Current responses are:
> > 
> > * 2 attendees
> >   
> >   * I've found multiple suggestions when you can meet with {name}:
> >   * I've found multiple suggestions when you can meet with {name}:
> >   * I've found the following time when you can meet with {name}:
> > * more than 2 attendees
> >   
> >   * I have found multiple suggestions:
> >   * There are multiple suggestions:
> >   * I found more than one suggestion:
> >   * Uh oh. I've found multiple suggestions:
> >   * There seem to be a few suggestions:
> > 
> > can we modify base on these responses?

**Comment by KayMKM** [comment]
fixed
