### ISSUE TITLE
update meeting flow for only one meeting

### ISSUE THREAD

**Issue by hibrenda** [microsoft/botframework-skills#341]
## Version
calendarv2

## Describe the bug
Give a clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/43408889/98078928-f8f65200-1ead-11eb-9950-e4ce83b9e6d4.png)
if only one meeting on the schedule, it does not show any detail info. 

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by KayMKM** [comment]
@Quirinevwm do we need show detail card if this is only one meeting is found? It could duplicate with the confirm card.

**Comment by Quirinevwm** [comment]
> @Quirinevwm do we need show detail card if this is only one meeting is found? It could duplicate with the confirm card.

We do need to show detail card when 1 meeting is found. 
Number 17 from overview bug list ->
![image](https://user-images.githubusercontent.com/43533472/98108983-2090ee80-1e9d-11eb-9881-96c90c4c62f7.png)

As discussed can you try out the 2 options and share - definitely recommend the (i) option!
(i) So can we first show the card, then prompt with confirm card?
(ii) first show confirm card and then show the details?

**Comment by KayMKM** [comment]
fixed
