### ISSUE TITLE
"Accepted" meeting event detail card does not have the right date

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-skills#346]
![image](https://user-images.githubusercontent.com/27976702/98093595-fad3fd00-1e3c-11eb-9aab-9677791536d9.png)

**Comment by xhr0804** [comment]
@lauren-mills I can't repro this issue, could you give more info?
![image](https://user-images.githubusercontent.com/44257569/98222940-6c6e9100-1f8c-11eb-9f41-7afa2723aab2.png)

**Comment by lauren-mills** [comment]
I made a change that caused this. Its resolved now!
