### ISSUE TITLE
Inconsistent button labels. "New meeting" vs. "New Event" vs. "Create a new meeting"

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-skills#347]
We have buttons for the same things throughout that have different text. For instance some we have three buttons for creating a new meeting that show different things as listed in the title. We should probably make these consistent

@Quirinevwm - what is your opinion here?

**Comment by Quirinevwm** [comment]
> d probably make these consistent
> 
> @Quirinevwm - what is your opinion here?

Yes I changed that to "new event" in the designs - it's shorter and fits better in a button. Will have a double check in transcript, I remember I spend some time on it. So the create and new meeting let's take that out!

**Comment by lauren-mills** [comment]
Resolved
