### ISSUE TITLE
Test/Bug: select AM/PM with date

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#350]
- Change order so it's clearer for the user
**1 AM on Wednesday, November 4, 2020
1 PM on Wednesday, November 4, 2020**
- Can we make sure when the user clicks on the selected button, that we hide the transcript and just pop-up the new card

![image](https://user-images.githubusercontent.com/43533472/98108004-98f6b000-1e9b-11eb-8059-331be098cd25.png)

**Comment by lauren-mills** [comment]
I've already started on this extension to the resolveDateTimeDialog
