### ISSUE TITLE
Test/Bug: confirmation card create event

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#351]
Can we include to show the card of meeting details BEFORE we've send out the calendar invite. 
This gives the user reassurance the invite is complete and ready to be send. 
Relates to part of #332 number 20
![image](https://user-images.githubusercontent.com/43533472/98110835-01479080-1ea0-11eb-9d13-5230c86f0aa6.png)

No need to show the card again once the invite has been send, just use the transcript from #332 number 11
**Alright, your event has been created.
I've added the meeting on your calendar.
OK, the event has been created for you.**

**Comment by KayMKM** [comment]
the card works on emulator but can't show in teams. I will investigate this.

**Comment by KayMKM** [comment]
fixed by #373
