### ISSUE TITLE
Test/Bug: loop in create with select AM/PM

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#356]
Infinite loop in create with selection time:
When I created a meeting & selected the right AM/PM time. The bot started over again and asked about "title" etc again.
![image](https://user-images.githubusercontent.com/43533472/98244838-57840480-1f70-11eb-84e4-4c9e2518c3b0.png)

**Comment by KayMKM** [comment]
@Quirinevwm I can't repro this.
![image](https://user-images.githubusercontent.com/19773357/99042770-4bc7bc00-25c8-11eb-86ca-fcb1937b2be1.png)

**Comment by Quirinevwm** [comment]
@KayMKM I think this issue was a duplicate and already updated, thanks it works!
