### ISSUE TITLE
Test/Bug: name contact missing in creation overview

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#357]
A/ when finalizing create step with meeting of 2 attendees (organizer + contact):
- missing attendee Name
![image](https://user-images.githubusercontent.com/43533472/98245056-a893f880-1f70-11eb-8408-2a670df99b98.png)

- card also missing (yue working on it #351 

B/ Also for overview of day with 1 meeting, transcript is off when it's just with 1 other attendee - should only include the [Name] not # more
![image](https://user-images.githubusercontent.com/43533472/98245483-4687c300-1f71-11eb-89d0-5303ca67288b.png)

**Comment by KayMKM** [comment]
A has been fixed, B duplicates with https://github.com/microsoft/botframework-skills/issues/359
