### ISSUE TITLE
Test/Bug: the first one in utterance was indication for logic

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#363]
Selection of a list element, the [first one] was meant as the indication to include the first line of text (name, suggestions time) in the utterance:

**Sure, I'll continue with [Name], [email adress].
Got it. I'll move forward with [Name], [email adress].
OK. I'll include [Name], [email adress]. as attendee.**

![image](https://user-images.githubusercontent.com/43533472/98373303-579f0580-203f-11eb-85b0-29670fec8dfc.png)

**Comment by KayMKM** [comment]
fixed by https://github.com/microsoft/botframework-skills/pull/393
