### ISSUE TITLE
Test/Bug: Asking about next week/month no response

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-skills#364]
4. Asking about next week/month no response, weekend works great (with carrousel for saturday/sunday)
image
![image](https://user-images.githubusercontent.com/44257569/98515814-9e426900-22a6-11eb-8877-c0cf4e137220.png)

In the design & transcript file we have different utterances and logic for:

weekend = show saturday/sunday in carrousel (that works in Teams load)
For the weekend, I see you have [#] events:
I see you have [#] events planned in the weekend:
Shows card for saturday/sunday

week/month = show just the upcoming Monday + additional transcript:
Next week, I see you have [#] events. First up on Monday:
Next month, I see you have [#] events. First up on Monday:
Shows card for monday

![image](https://user-images.githubusercontent.com/44257569/98515883-bf0abe80-22a6-11eb-99f6-c501fd0fae38.png)

**Comment by lauren-mills** [comment]
Because we don't know whether they requested "next week" or "next month" from the resolved date time, just say "You have [#] events planned from [start date] to [end date]. First up on [first day of date range]:"
