### ISSUE TITLE
Test/Bug: Paging (find) does not work

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-skills#365]
Paging (find) does not work, it auto populates a new card and logic is weird now - can we try the update status
![image](https://user-images.githubusercontent.com/44257569/98516398-6c7dd200-22a7-11eb-876e-9586b0fc6669.png)

? Do we need to show "next page" when the user clicks - or can we hide that in a way?

**Comment by xhr0804** [comment]
![image](https://user-images.githubusercontent.com/44257569/98517507-fb3f1e80-22a8-11eb-9f01-e8714dd239b4.png)
? Do we need to show "next page" when the user clicks - or can we hide that in a way?

**Comment by xhr0804** [comment]
@Quirinevwm Do you mean change the card in place by clicking "next page" button but not show a new one?

**Comment by Quirinevwm** [comment]
> @Quirinevwm Do you mean change the card in place by clicking "next page" button but not show a new one?

I think @lauren-mills has been looking at this and updated the card already, so there is:
- no transcript for next page is shown 
- the card updates itself!

**Comment by xhr0804** [comment]
@Quirinevwm yes it works now, let's close the issue.
