### ISSUE TITLE
Test/Bug: For create flow, it's the voice script which is fine, but do we want to call that out? I think it's nice to highlight there will be a Teams form - otherwise we will get that feedback probably.

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-skills#366]
For create flow, it's the voice script which is fine, but do we want to call that out? I think it's nice to highlight there will be a Teams form - otherwise we will get that feedback probably.

**Comment by lauren-mills** [comment]
We can call this out in the powerpoint. No need to modify the bot I don't think
