### ISSUE TITLE
Test/Bug: Select attendee, the click is not working, you need to call out the number or exact surname

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-skills#367]
Select attendee, the click is not working, you need to call out the number or exact surname
![image](https://user-images.githubusercontent.com/44257569/98517035-486ec080-22a8-11eb-8392-56a7f34521a8.png)

**Comment by KayMKM** [comment]
@Quirinevwm I can't repro this issue. Could you verify?

**Comment by Quirinevwm** [comment]
> @Quirinevwm I can't repro this issue. Could you verify?

Yes the clicking an element is working (Lauren fixed that), but the name selection is not - see #368 for latest example

**Comment by KayMKM** [comment]
> > @Quirinevwm I can't repro this issue. Could you verify?
> 
> Yes the clicking an element is working (Lauren fixed that), but the name selection is not - see #368 for latest example

Ok, so let's track this issue in 368
