### ISSUE TITLE
Test/Bug: error when choose contacts

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-skills#368]
I get the wrong follow-up, that is transcript from search event: I could not find the event you are looking for - when I'm in finding contact step. When there is not match or an error, it should be from the transcript Excel:
**I couldn't find relevant contacts to add. Want to try again?
Hmm. I couldn't find any matching contact. Should we try again?
I don't see any matching contacts. Can you repeat the name or email address again?**
![image](https://user-images.githubusercontent.com/44257569/98517953-ac45b900-22a9-11eb-9f78-a8c2157ccad0.png)
![image](https://user-images.githubusercontent.com/44257569/98518122-eca53700-22a9-11eb-80b3-275e3a862234.png)

**Comment by KayMKM** [comment]
@Quirinevwm I can't repro this issue. Could verify it in current version?

**Comment by Quirinevwm** [comment]
> e. Could ver

Yes some of that is old and fixed I know Lauren has updated, the first (1st to work0 & clicking on the element. 
What is going wrong still is the following: 
- When I call out the full name: it does not recognize the selection
- Confirmation transcript is missing when I select a contact via (first, 1st)
![image](https://user-images.githubusercontent.com/43533472/98552759-24f34800-229f-11eb-8b5c-4f1c97d9cbe0.png)

**Comment by KayMKM** [comment]
fixed by https://github.com/microsoft/botframework-skills/pull/393
