### ISSUE TITLE
Test/Bug: Follow-up on selecting contacts keep on popping-up:

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-skills#369]
Follow-up on selecting contacts keep on popping-up:
![image](https://user-images.githubusercontent.com/44257569/98518630-97b5f080-22aa-11eb-9b5e-960a2e7007da.png)
When I click on a meeting in the list - I get again the select contact card (so not the detail card of the selected meeting) with additional transcript:
![image](https://user-images.githubusercontent.com/44257569/98518661-a13f5880-22aa-11eb-9a71-203f733e3d59.png)

**Comment by KayMKM** [comment]
fixed
