### ISSUE TITLE
Test/Bug: Search suggestion of AM/PM is enough

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-skills#370]
Search suggestion of AM/PM is enough I think, no need to display the date of tomorrow as well (since you can't adjust that anyways). The transcript for "when is my next meeting, how long till my meeting" is used here, can we rely on - what transcript:
"I found a meeting on [Date], at [Time] [AM/PM], [Name of event]. The attendees are [Name 1], and [#] more."
![image](https://user-images.githubusercontent.com/44257569/98519224-6b4ea400-22ab-11eb-990d-e93c4bc89f0d.png)
For tomorrow, it shows the date (we can take that out and just ask for time). If there are multiple it does not show the options in the list just one:
![image](https://user-images.githubusercontent.com/44257569/98519355-a18c2380-22ab-11eb-8b90-a2a8ce13a8fa.png)
For other day in the week: take out options in the past, then showing date makes sense!
![image](https://user-images.githubusercontent.com/44257569/98519524-d6987600-22ab-11eb-9414-fa558a010325.png)

**Comment by Quirinevwm** [comment]
To add I think all of this is fixed, just as double check for Dogfood!

**Comment by lauren-mills** [comment]
Everything here is fixed except removing the date when you ask for "tomorrow at 3" from the disambiguation card. That's actually a bit complicated because it requires special logic just for tomorrow so I suggest we postpone until after dogfood. Everything else should be resolved in PR #396
