### ISSUE TITLE
Test/Bug: Can not find specific meeting when there are lots of meetings before it

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-skills#378]
I have a meeting named "plan".
When I set this meeting on Nov.16, I can find it. But if I move it to Nov.20, I cann't find it.
![image](https://user-images.githubusercontent.com/44257569/98791452-0d9f9080-2440-11eb-8758-230f001ceb04.png)
![image](https://user-images.githubusercontent.com/44257569/98791389-f660a300-243f-11eb-8cba-1a1ef82da676.png)

**Comment by xhr0804** [comment]
@lauren-mills This may be because of the maximum limit of 25 event to be found. Maybe we should add the limit to the output instead of the number of events to be searched?
And @KayMKM is also working on adding similar limits to Contact/SuggestTime list, maybe we should use the same pattern for this like add a parameter “MaxResults” to the CustomAction?

**Comment by lauren-mills** [comment]
Isn’t there a default date range for the next week on the action right now? I believe we only search the next week if the date is not provided in the utterance

**Comment by lauren-mills** [comment]
Regardless, we should add the limit to the results rather than the api call. I applied it there to try to reduce the long time it takes to get the search results back for longer queries but we could lose results with the current implementation

**Comment by xhr0804** [comment]
@lauren-mills Is this the new change? I remember Quirine suggested 1 month for the default date range

**Comment by Quirinevwm** [comment]
For logic I propose we go for the following:
- Show 25 results that is the limit of the output relating to the "search"
- Within 1 month timeframe, that will be the limit of the overall query
Only one week is not enough to search by that is relevant for the user
