### ISSUE TITLE
Test/Bug: confirm in text instead of button not working

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#384]
When typing in confirm, it does not confirm the event.
The button action works, it's just the transcript asks for "ready to send"
So yes to this answer = the same as confirm (add to LG)
![image](https://user-images.githubusercontent.com/43533472/98828227-1b511800-2438-11eb-9d5d-bb1ffcfa7eb8.png)

**Comment by KayMKM** [comment]
fixed
