### ISSUE TITLE
Test/Bug: transcript for no results "find"

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#385]
The repetitive transcript, can we rely on what's in the Excel:
![image](https://user-images.githubusercontent.com/43533472/98828956-f4dfac80-2438-11eb-96b0-6346b95b9689.png)

**I couldn't find the event that you're looking for. Let's try your search again. Can you tell me the specific title, start date, or attendees?
I don't see a meeting with that [title/date/time]. Can you tell me more about the meeting you're looking for, like the start time, title of the event, or other attendees?**

2x try unsuccesful
**Hmm. I still can't find the event you're looking for. You have [# meetings] today, etc... (show list of meetings)
Something seems to be going wrong. I can tell you more about your meetings today... (show list of meetings)**

**Comment by xhr0804** [comment]
@Quirinevwm As shown bellow, in current flow, if user just says "find a meeting“ without any condition, there will be an extra step "0" to ask for the search condition. If user says "find a meeting by [condition]" at the beginning, there will only be two steps(without step 0).
Do you think this design is OK? And besides the 1st/2nd try, do you want to add new transcript to step 0, or just skip step0 and just keep the remaining 2 steps.
![image](https://user-images.githubusercontent.com/44257569/98933801-18c7ee80-251c-11eb-8965-90d3d7039d71.png)

**Comment by Quirinevwm** [comment]
@xhr0804 you are right we need to add additional transcript - it's too repetitive (and should be used as alterations). Plus the show what's on for today without checking seems to be very odd indeed. 

So I propose
**Try 1:**
- I couldn't find the event that you're looking for. Let's try your search again. Can you tell me the specific title, start date, or attendees?
- I don't see a meeting with that [title/date/time]. Can you tell me more about the meeting you're looking for, like the start time, title of the event, or other attendees?

**Try 2:**
- Still couldn't find the event. Can you try again?

**Try 3:**
- Hmm. I still can't find the event you're looking for. Want to hear more about your meetings today?
- Something seems to be going wrong. I can tell you more about your meetings today if you like?
Yes -> Generic transcript: I found 5...
No -> Generic transcrtip: OK,
