### ISSUE TITLE
Test/Bug: when asking about overview calendar for a specific day, it shows another day

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#386]
When user asks about a [day/Friday], the bot asks to clarify which upcoming Friday. Then by selecting the right Friday, the next Monday is shown.
The bot should just show the calendar for that selected day
(I know this probably is happening due to the Monday display when a user asks for week/month - please look into that)
![image](https://user-images.githubusercontent.com/43533472/98829275-50119f00-2439-11eb-93f3-183badd80e75.png)

**Comment by lauren-mills** [comment]
@Quirinevwm - I wasn't able to repro this. Can you try again and let me know if this is still happening for you?

![image](https://user-images.githubusercontent.com/27976702/99047939-c69dc200-2549-11eb-81ab-83e317330d37.png)

**Comment by Quirinevwm** [comment]
@lauren-mills in general I would like to think that we only show Friday's in the future (so not the 6th), so that by coincidence would mean today (Friday the 13th). If we are not completely sure I'd rather show Friday (today) and next week.

I'm not getting any response back:
![image](https://user-images.githubusercontent.com/43533472/99058505-954ee180-259d-11eb-8c19-0cf76eb9503e.png)

**Comment by lauren-mills** [comment]
I'm publishing a change now that removes the options that are in the past so hopefully that helps resolve.

**Comment by lauren-mills** [comment]
Changes are published, so try it out and let me know or close the issue if it works for you now

**Comment by Quirinevwm** [comment]
I tried for friday, and now I can't get overview of day to work:
![image](https://user-images.githubusercontent.com/43533472/99065534-d3510300-25a7-11eb-8e5e-1e012de7a9cb.png)

![image](https://user-images.githubusercontent.com/43533472/99065606-f085d180-25a7-11eb-8b1e-8e29124922f8.png)

**Comment by lauren-mills** [comment]
I think this may be resolved now. I tried each of these utterances and they worked for me now.

**Comment by Quirinevwm** [comment]
@lauren-mills yes almost all of them are working as they should!
All the logic is in place and happens!!
- what's on my calendar -> today and shows suggestive action for tomorrow
- happening tomorrow -> suggestive action next day ;)
- on Friday -> shows my upcoming Friday next week (perfecto no need to pick from a previous date)

Only thing that does not route nicely is - "when is my next meeting" "What is my next meeting"
Then I think we are all set for the dogfood

![image](https://user-images.githubusercontent.com/43533472/99148666-47170c80-2689-11eb-913b-760955d4c0f6.png)
