### ISSUE TITLE
Test/Bug: too verbose when no attendees 

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-skills#387]
Keep the first line of transcript + the "Proceed without..." as suggestive button
![image](https://user-images.githubusercontent.com/43533472/98842305-a686d980-2449-11eb-9c27-0058fb77c6c0.png)

**Comment by KayMKM** [comment]
@Quirinevwm should we also remove the reprompt "who do you want to invite"? If user just typo, they will can't add attendee at this time.

**Comment by KayMKM** [comment]
new retry logic:
![image](https://user-images.githubusercontent.com/19773357/99051081-41f78600-25d3-11eb-904c-d47afbccf8ac.png)
![image](https://user-images.githubusercontent.com/19773357/99051322-5471bf80-25d3-11eb-9c6b-bac3fb9f75d8.png)

**Comment by Quirinevwm** [comment]
@KayMKM yes this revised logic is good! I think "who do you want to invite" is just a variation of "Who will join" - so that is correct behaviour
