### ISSUE TITLE
[Calendar Skill V2] 

### ISSUE THREAD

**Issue by ToddN** [microsoft/botframework-skills#399]
## Describe the bug
Give a clear and concise description of what the bug is. 

Sign in to the web version seems to have failed and I can't figure out how to retry
## To Reproduce
Steps to reproduce the behavior. What utterances or buttons didn't work?
I went through the step of adding the bot, then it asked me to sign in. It popped up the auth window, lowered it, but then sends a messages that indicates that I'm not signed in.
![image](https://user-images.githubusercontent.com/6475741/99298099-0a205680-27fe-11eb-8d50-6b7e53f0583a.png)

## Expected behavior
Give a clear and concise description of what you expected to happen.
If sign in fails, there should be a way to retry.  I tried saying "sign out" but it says sign in.  If I say "sign in" it still says "You're signing out."

**Comment by lauren-mills** [comment]
If you get logged out, you can still ask questions and it will prompt you to log in again.
