### ISSUE TITLE
[skills] Action support alignment

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-skills#41]
#### What project is affected?
skills
#### What happens?
In current implementation of action support, but here are something need to be aligned
1. Add a flag IsAction in the state
2. actionSuccess should be in every return result structure
3. Use the flag to check the dialog is in action mode or not, and just return actionResult when the dialog is in action mode. 
4. Check whether the action succeed in the FinalStep

**Comment by bobokids** [comment]
Resolved in action support for all skills.
