### ISSUE TITLE
Remove .tt files in Skills for responses

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botframework-skills#52]
#### What project is affected?
All skills

#### What language is this in?
C#

#### What happens?
The .tt files in the skills should be removed to align with the SDK team's LG approach.

**Comment by xieofxie** [comment]
Hi @lauren-mills currently for lg, we use tt file to extract names from lg files and then use these constant variables in code with auto-suggestion support instead of copy-paste everywhere. Should we keep it?

**Comment by lauren-mills** [comment]
We should remove it. If we want this sort of functionality for LG we should raise a request on the botbuilder repo instead. The reason for removing it is to reduce the number of unique concepts a developer needs to learn to work with our projects.

**Comment by xieofxie** [comment]
OK

**Comment by DingmaomaoBJTU** [comment]
An issue had been created for this: https://github.com/microsoft/botbuilder-tools/issues/1235

**Comment by bobokids** [comment]
Closed
