### ISSUE TITLE
Calendar Meeting room booking CosmosDB error

### ISSUE THREAD

**Issue by gagankohli2000** [microsoft/botframework-skills#54]
#### What project is affected?
Calendar Skill

#### What language is this in?
c#
#### What happens?
Getting below error while deploying meeting room booking solution

![CosmosDBerror](https://user-images.githubusercontent.com/14933211/76384712-cf833600-63b3-11ea-9e96-ffd3c4b08d9a.png)

**Comment by ryanlengel** [comment]
Transferring to the [microsoft/botframework-skills](https://github.com/microsoft/botframework-skills] repository.

**Comment by xhr0804** [comment]
The main reason is that the CosmosDB package is not installed.
You can manually install it in powershell by
`Install-Module -Name CosmosDB`
Will add the prerequisites in the doc.

**Comment by gagankohli2000** [comment]
Thanks. Also note that it is not letting install CosmosDB package as system already has updated az login commands. We need to use cobble parameter
