### ISSUE TITLE
[Skills] handle cancel/logout alignment

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-skills#77]
## User Story
As ...
I want ...
so that ...

## Acceptance Criteria 
*List your requirements.*
- [ ] ... Create parity for https://github.com/microsoft/botframework-solutions/pull/3154
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by bobokids** [comment]
all skills done.
