### ISSUE TITLE
[Skills] deployment script update

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botframework-skills#78]
#### What project is affected?
All skills
#### What happens?
1. Align deployment script to skill template

2. change the  "group deployment" to "deployment group"
![image](https://user-images.githubusercontent.com/44257569/76736573-04bbc980-67a2-11ea-8cbf-fab94e09d91f.png)

**Comment by xieofxie** [comment]
Update template first? 
Found this https://github.com/microsoft/botframework-solutions/pull/3184/files
Also could copy and adapt the script to here https://github.com/microsoft/botframework-solutions/blob/master/tools/scripts/synchronize_deploy_scripts.ps1

Maybe you could post a message in Teams that when skill template update, they should open an issue here to inform us
