### ISSUE TITLE
[Email skill] support Delete scenario

### ISSUE THREAD

**Issue by bobokids** [microsoft/botframework-skills#79]
## User Story
As ...  a skill user
I want ... to delete email via email bot
so that ... I can get better user experience

Em has the design:
![image](https://user-images.githubusercontent.com/19182479/76741841-2a999c00-67ab-11ea-8b0a-f1bf89d3f20e.png)

## Acceptance Criteria 
*List your requirements.*
- [ ] ... user can delete an email using the flow as Em's design
- [ ] ...
- [ ] ...

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

## Notes
*Provide any additional information.*

**Comment by KayMKM** [comment]
For supporting this scenario by smallest impact. I reused old logic in email:
![image](https://user-images.githubusercontent.com/19773357/76912532-38583a00-68ef-11ea-985b-25aeec557ca8.png)
![image](https://user-images.githubusercontent.com/19773357/76912560-4efe9100-68ef-11ea-9c52-a64d19db12da.png)
![image](https://user-images.githubusercontent.com/19773357/76912595-663d7e80-68ef-11ea-8a95-7e66c4f31d7d.png)
