### ISSUE TITLE
[Email] Oauth card can't show up on DLS channel

### ISSUE THREAD

**Issue by KayMKM** [microsoft/botframework-skills#92]
#### What project is affected?
Email

#### What happens?
![image](https://user-images.githubusercontent.com/19773357/76963280-be11cf00-695b-11ea-87bb-21863031654f.png)

#### What are the steps to reproduce this issue?
link Email skill by DLS channel

#### What were you expecting to happen?
the skill works well

**Comment by xieofxie** [comment]
Create an issue here? https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/issues

**Comment by KayMKM** [comment]
> Create an issue here? https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/issues

Sure. Let's track the issue here: https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/issues/91

**Comment by bobokids** [comment]
Close this issue. We had an issue on speech team to track.
