### ISSUE TITLE
[Weather] error when showing weather in VA

### ISSUE THREAD

**Issue by bobokids** [microsoft/botframework-skills#96]
#### What project is affected?
Weather skill

#### What language is this in?
all

#### What happens?
Error when query weather in VA

#### What are the steps to reproduce this issue?
. launch VA+weather skill
. input "what's the weather in Beijing?"
. bot prompt error message

#### Any screenshots or additional context?
![image](https://user-images.githubusercontent.com/19182479/76970898-78f39a00-6967-11ea-913f-f191e41a78b2.png)

**Comment by ssss141414** [comment]
https://github.com/microsoft/botframework-skills/pull/97
